[package]
name = "imvr"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
glam = "0.24"
image = "0.24"
wgpu = { version = "0.17", features = ["spirv"] }
winit = "0.29.0-beta.0"
anyhow = "1.0"

log = "0.4"
env_logger = "0.10"
